package blue.coordination.processor;

import blue.repo.BlueRepository;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Release-input guards for the final report generated by Gradle after every
 * release-gating suite has completed.
 */
class SelectiveProcessingReportArtifactTest {
    private static final Path PROJECT_DIRECTORY = Paths.get(
            System.getProperty("user.dir"))
            .toAbsolutePath()
            .normalize();

    @Test
    void shouldResolveEveryRequiredFixedRepositoryTypeByManifestBlueId()
            throws Exception {
        // given
        BlueRepository repository = BlueRepository.latest();

        // when
        List<CoordinationRequiredRepositoryClosure.Entry> requiredTypes =
                CoordinationRequiredRepositoryClosure.entries();

        // then
        assertFalse(
                requiredTypes.isEmpty());
        assertEquals(
                CoordinationRequiredRepositoryClosure
                        .REPOSITORY_VERSION,
                repository.repositoryVersion());
        assertEquals(
                CoordinationRequiredRepositoryClosure
                        .REPOSITORY_MANIFEST_BLUE_ID,
                repository.repositoryVersionBlueId());
        for (CoordinationRequiredRepositoryClosure.Entry required
                : requiredTypes) {
            assertEquals(
                    required.blueId(),
                    repository.blueId(
                            required.qualifiedName()),
                    required.qualifiedName());
            assertNotNull(
                    repository.nodeByBlueId(
                            required.blueId())
                            .orElse(null),
                    required.qualifiedName());
        }
    }

    @Test
    void shouldRequireOnlyLocalBlueSiblingCompositeBuilds()
            throws Exception {
        // given
        String settings = read("settings.gradle");
        String build = read("build.gradle");

        // when
        boolean languageLocal = settings.contains(
                "includeBuild(localBlueLanguage)");
        boolean bexLocal = settings.contains(
                "includeBuild(localBlueBex)");
        boolean repositoryLocal = settings.contains(
                "includeBuild(immutableBlueRepository)");

        // then
        assertTrue(languageLocal);
        assertTrue(bexLocal);
        assertTrue(repositoryLocal);
        assertTrue(settings.contains(
                "substitute module('blue.language:blue-language-java')"));
        assertTrue(settings.contains(
                "substitute module('blue.bex:blue-bex-java')"));
        assertTrue(settings.contains(
                "substitute module('blue.repo:blue-repo-java')"));
        assertTrue(settings.contains(
                "blueRepositoryCompositePath"));
        assertTrue(settings.contains(
                "'--no-hardlinks'"));
        assertTrue(build.contains("excludeGroup 'blue.language'"));
        assertTrue(build.contains("excludeGroup 'blue.bex'"));
        assertTrue(build.contains("excludeGroup 'blue.repo'"));
    }

    @Test
    void shouldContainNoUnfinishedDeliveredSourceMarkers()
            throws Exception {
        // given
        List<Path> deliveredSources = Arrays.asList(
                PROJECT_DIRECTORY.resolve(
                        "src/main/java"),
                PROJECT_DIRECTORY.resolve(
                        "src/jmh/java"));
        StringBuilder source = new StringBuilder();

        // when
        for (Path deliveredSource
                : deliveredSources) {
            try (Stream<Path> files =
                         Files.walk(deliveredSource)) {
                files.filter(Files::isRegularFile)
                        .filter(path -> path.toString()
                                .endsWith(".java"))
                        .sorted()
                        .forEach(path -> source.append(
                                uncheckedRead(path)));
            }
        }

        // then
        assertFalse(source.toString().contains("@Deprecated"));
        assertFalse(source.toString().contains("TODO"));
        assertFalse(source.toString().contains("FIXME"));
    }

    private static String read(String relative)
            throws Exception {
        return new String(
                Files.readAllBytes(
                        PROJECT_DIRECTORY.resolve(relative)),
                StandardCharsets.UTF_8);
    }

    private static String uncheckedRead(Path path) {
        try {
            return new String(
                    Files.readAllBytes(path),
                    StandardCharsets.UTF_8);
        } catch (java.io.IOException exception) {
            throw new IllegalStateException(
                    "Could not inspect " + path,
                    exception);
        }
    }
}
